#!/usr/bin/python
import os,time,sys
H='/sys/bus/i2c/devices/0-002e'
C=[(50,25),(58,32),(63,45),(68,60),(73,85),(78,130),(85,200),(92,255)]
def ri(p):
 try: return int(open(p).read())
 except: return None
def wi(p,v):
 try:
  f=open(p,'w'); f.write('%d\n'%v); f.close(); return 1
 except: return 0
def temp():
 vs=[]
 for n in ('temp6_input','temp7_input'):
  v=ri(H+'/'+n)
  if v and v>0: vs.append(v/1000.0)
 return max(vs) if vs else None
def pwm(t):
 if t<=C[0][0]: return C[0][1]
 if t>=C[-1][0]: return C[-1][1]
 for i in range(1,len(C)):
  t0,p0=C[i-1]; t1,p1=C[i]
  if t<=t1: return int(p0+(t-t0)/float(t1-t0)*(p1-p0))
 return C[-1][1]
def setp(p):
 p=max(20,min(255,int(p)))
 for i in range(1,5):
  wi(H+'/pwm%d_mode'%i,0); wi(H+'/pwm%d_input'%i,p)
 return p
for i in range(90):
 if os.path.exists(H+'/pwm1_input'): break
 time.sleep(1)
else:
 sys.stderr.write('quietfan: no hw\n'); sys.exit(1)
cur=None; lt=None
while 1:
 t=temp()
 if t is None:
  time.sleep(4); continue
 tgt=pwm(t)
 if cur is not None and tgt<cur and lt is not None and t>lt-2:
  tgt=cur
 if cur!=tgt:
  setp(tgt); cur=tgt; lt=t
  print 'quietfan: temp=%.1fC pwm=%d'%(t,cur)
 time.sleep(4)
